name: 'Lint perl'
on:
  workflow_dispatch:
  pull_request:

permissions:
  checks: write
  contents: read    # Best practice: explicit add 'read' when adding other rights

jobs:
  linux:
    name: Running lint on Slim/ folder...
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Get all history to create a diff later
          
      - name: Install dependencies
        if: ${{ !env.ACT }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libperl-critic-perl libio-socket-ssl-perl libnet-ssleay-perl netcat-traditional
          version: 1

      - name: Get changed files
        id: files
        run: |
          # Haal de doel-branch op (meestal main of master)
          git fetch origin ${{ github.base_ref }}
          
          # Vergelijk de huidige commit met de basis van de PR
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '\.(pm|pl)$' | xargs)
          
          echo "changed_files=$CHANGED" >> $GITHUB_OUTPUT
          
      - name: Register problem matcher
        run: echo "::add-matcher::.github/perlcritic-matcher.json"

      - name: Run perlcritic
        run: perlcritic --severity 5 --verbose "%f:%l:%c:%m\n" ${{ steps.files.outputs.changed_files }}

