name: 'Lint perl'
on:
  workflow_dispatch:
jobs:
  linux:
    name: Running lint on Slim/ folder...
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        if: ${{ !env.ACT }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libperl-critic-perl libio-socket-ssl-perl libnet-ssleay-perl netcat-traditional
          version: 1

      - name: Lint Slim/
        run: perlcritic --severity 4 --verbose 8 Slim/

