name: 'Lint perl'
on:
  workflow_dispatch:
  pull_request:

permissions:
  checks: write
  contents: read    # Best practice: explicit add 'read' when adding other rights

jobs:
  linux:
    name: Running lint on Slim/ folder...
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        if: ${{ !env.ACT }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libperl-critic-perl libio-socket-ssl-perl libnet-ssleay-perl netcat-traditional
          version: 1

      - name: Register Problem Matcher
        run: echo "::add-matcher::.github/perlcritic-matcher.json"

      - name: Lint Slim/
        # --verbose 1 ensures the output is in the "file at line X, column Y" format
        run: perlcritic --severity 5 --verbose 1 Slim/

