name: 'Perlcritic'
on:
  workflow_dispatch:
  pull_request:

permissions:
  checks: write
  contents: read    # Best practice: explicit add 'read' when adding other rights

jobs:
  linux:
    name: Running Perlcritic...
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
          
      - name: Install dependencies
        if: ${{ !env.ACT }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libperl-critic-perl
          version: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Register problem matcher
        run: echo "::add-matcher::.github/perlcritic-matcher.json"
          
      - name: Run perlcritic
        run: |
          perlcritic --severity 5 --nocolor --verbose "%f:%l:%c:%m\n" ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Remove problem matcher
        run: echo "::remove-matcher owner=perlcritic::"
